#pragma once

#include <unordered_map>
#include <string>

static const std::unordered_map<std::string, std::string> ISO_639_2_TO_ENGLISH
{
    { "aar", "Afar" },
    { "abk", "Abkhazian" },
    { "ace", "Achinese" },
    { "ach", "Acoli" },
    { "ada", "Adangme" },
    { "ady", "Adyghe" },
    { "afa", "Afro-Asiatic" },
    { "afh", "Afrihili" },
    { "afr", "Afrikaans" },
    { "ain", "Ainu" },
    { "aka", "Akan" },
    { "akk", "Akkadian" },
    { "alb", "Albanian" },
    { "ale", "Aleut" },
    { "alg", "Algonquian" },
    { "alt", "Southern Altai" },
    { "amh", "Amharic" },
    { "ang", "Old English" },
    { "anp", "Angika" },
    { "apa", "Apache" },
    { "ara", "Arabic" },
    { "arc", "Official Aramaic" },
    { "arg", "Aragonese" },
    { "arm", "Armenian" },
    { "arn", "Mapudungun" },
    { "arp", "Arapaho" },
    { "art", "Artificial" },
    { "arw", "Arawak" },
    { "asm", "Assamese" },
    { "ast", "Asturian" },
    { "ath", "Athapascan" },
    { "aus", "Australian" },
    { "ava", "Avaric" },
    { "ave", "Avestan" },
    { "awa", "Awadhi" },
    { "aym", "Aymara" },
    { "aze", "Azerbaijani" },
    { "bad", "Banda" },
    { "bai", "Bamileke" },
    { "bak", "Bashkir" },
    { "bal", "Baluchi" },
    { "bam", "Bambara" },
    { "ban", "Balinese" },
    { "baq", "Basque" },
    { "bas", "Basa" },
    { "bat", "Baltic" },
    { "bej", "Beja" },
    { "bel", "Belarusian" },
    { "bem", "Bemba" },
    { "ben", "Bengali" },
    { "ber", "Berber" },
    { "bho", "Bhojpuri" },
    { "bih", "Bihari" },
    { "bik", "Bikol" },
    { "bin", "Bini" },
    { "bis", "Bislama" },
    { "bla", "Siksika" },
    { "bnt", "Bantu" },
    { "bod", "Tibetan" },
    { "bos", "Bosnian" },
    { "bra", "Braj" },
    { "bre", "Breton" },
    { "btk", "Batak" },
    { "bua", "Buriat" },
    { "bug", "Buginese" },
    { "bul", "Bulgarian" },
    { "bur", "Burmese" },
    { "byn", "Blin" },
    { "cad", "Caddo" },
    { "cai", "Central American Indian" },
    { "car", "Galibi Carib" },
    { "cat", "Catalan" },
    { "cau", "Caucasian" },
    { "ceb", "Cebuano" },
    { "cel", "Celtic" },
    { "ces", "Czech" },
    { "cha", "Chamorro" },
    { "chb", "Chibcha" },
    { "che", "Chechen" },
    { "chg", "Chagatai" },
    { "chi", "Chinese" },
    { "chk", "Chuukese" },
    { "chm", "Mari" },
    { "chn", "Chinook jargon" },
    { "cho", "Choctaw" },
    { "chp", "Chipewyan" },
    { "chr", "Cherokee" },
    { "chu", "Old Slavonic" },
    { "chv", "Chuvash" },
    { "chy", "Cheyenne" },
    { "cmc", "Chamic" },
    { "cnr", "Montenegrin" },
    { "cop", "Coptic" },
    { "cor", "Cornish" },
    { "cos", "Corsican" },
    { "cpe", "Creoles and pidgins (English based)" },
    { "cpf", "Creoles and pidgins (French based)" },
    { "cpp", "Creoles and pidgins (Portugese based)" },
    { "cre", "Cree" },
    { "crh", "Crimean Tatar" },
    { "crp", "Creoles and pidgins" },
    { "csb", "Kashubian" },
    { "cus", "Cushitic" },
    { "cym", "Welsh" },
    { "cze", "Czech" },
    { "dak", "Dakota" },
    { "dan", "Danish" },
    { "dar", "Dargwa" },
    { "day", "Land Dayak" },
    { "del", "Delaware" },
    { "den", "Slave (Athapascan)" },
    { "deu", "German" },
    { "dgr", "Dogrib" },
    { "din", "Dinka" },
    { "div", "Maldivian" },
    { "doi", "Dogri" },
    { "dra", "Dravidian" },
    { "dsb", "Lower Sorbian" },
    { "dua", "Duala" },
    { "dum", "Middle Dutch" },
    { "dut", "Dutch" },
    { "dyu", "Dyula" },
    { "dzo", "Dzongkha" },
    { "efi", "Efik" },
    { "egy", "Egyptian" },
    { "eka", "Ekajuk" },
    { "ell", "Greek" },
    { "elx", "Elamite" },
    { "eng", "English" },
    { "enm", "Middle English" },
    { "epo", "Esperanto" },
    { "est", "Estonian" },
    { "eus", "Basque" },
    { "ewe", "Ewe" },
    { "ewo", "Ewondo" },
    { "fan", "Fang" },
    { "fao", "Faroese" },
    { "fas", "Persian" },
    { "fat", "Fanti" },
    { "fij", "Fijian" },
    { "fil", "Filipino" },
    { "fin", "Finnish" },
    { "fiu", "Finno-Ugrian" },
    { "fon", "Fon" },
    { "fra", "French" },
    { "fre", "French" },
    { "frm", "Middle French" },
    { "fro", "Old French" },
    { "frr", "Northern Frisian" },
    { "frs", "Eastern Frisian" },
    { "fry", "Western Frisian" },
    { "ful", "Fulan" },
    { "fur", "Friulian" },
    { "gaa", "Ga" },
    { "gay", "Gayo" },
    { "gba", "Gbaya" },
    { "gem", "Germanic" },
    { "geo", "Georgian" },
    { "ger", "German" },
    { "gez", "Geez" },
    { "gil", "Gilbertese" },
    { "gla", "Gaelic" },
    { "gle", "Irish" },
    { "glg", "Galician" },
    { "glv", "Manx" },
    { "gmh", "Middle High German" },
    { "goh", "Old High German" },
    { "gon", "Gondi" },
    { "gor", "Gorontalo" },
    { "got", "Gothic" },
    { "grb", "Grebo" },
    { "grc", "Ancient Greek" },
    { "gre", "Greek" },
    { "grn", "Guarani" },
    { "gsw", "Swiss German" },
    { "guj", "Gujarati" },
    { "gwi", "Gwich'in" },
    { "hai", "Haida" },
    { "hat", "Haitian" },
    { "hau", "Hausa" },
    { "haw", "Hawaiian" },
    { "heb", "Hebrew" },
    { "her", "Herero" },
    { "hil", "Hiligaynon" },
    { "him", "Himachali" },
    { "hin", "Hindi" },
    { "hit", "Hittite" },
    { "hmn", "Hmong" },
    { "hmo", "Hiri Motu" },
    { "hrv", "Croatian" },
    { "hsb", "Upper Sorbian" },
    { "hun", "Hungarian" },
    { "hup", "Hupa" },
    { "hye", "Armenian" },
    { "iba", "Iban" },
    { "ibo", "Igbo" },
    { "ice", "Icelandic" },
    { "ido", "Ido" },
    { "iii", "Sichuan Yi" },
    { "ijo", "Ijo" },
    { "iku", "Inuktitut" },
    { "ile", "Interlingue" },
    { "ilo", "Iloko" },
    { "ina", "Interlingua" },
    { "inc", "Indic" },
    { "ind", "Indonesian" },
    { "ine", "Indo-European" },
    { "inh", "Ingush" },
    { "ipk", "Inupiaq" },
    { "ira", "Iranian" },
    { "iro", "Iroquoian" },
    { "isl", "Icelandic" },
    { "ita", "Italian" },
    { "jav", "Javanese" },
    { "jbo", "Lojban" },
    { "jpn", "Japanese" },
    { "jpr", "Judeo-Persian" },
    { "jrb", "Judeo-Arabic" },
    { "kaa", "Kara-Kalpak" },
    { "kab", "Kabyle" },
    { "kac", "Kachin" },
    { "kal", "Greenlandic" },
    { "kam", "Kamba" },
    { "kan", "Kannada" },
    { "kar", "Karen" },
    { "kas", "Kashmiri" },
    { "kat", "Georgian" },
    { "kau", "Kanuri" },
    { "kaw", "Kawi" },
    { "kaz", "Kazakh" },
    { "kbd", "Kabardian" },
    { "kha", "Khasi" },
    { "khi", "Khoisan" },
    { "khm", "Central Khmer" },
    { "kho", "Khotanese" },
    { "kik", "Kikuyu" },
    { "kin", "Kinyarwanda" },
    { "kir", "Kirghiz" },
    { "kmb", "Kimbundu" },
    { "kok", "Konkani" },
    { "kom", "Komi" },
    { "kon", "Kongo" },
    { "kor", "Korean" },
    { "kos", "Kosraean" },
    { "kpe", "Kpelle" },
    { "krc", "Karachay-Balkar" },
    { "krl", "Karelian" },
    { "kro", "Kru" },
    { "kru", "Kurukh" },
    { "kua", "Kwanyama" },
    { "kum", "Kumyk" },
    { "kur", "Kurdish" },
    { "kut", "Kutenai" },
    { "lad", "Ladino" },
    { "lah", "Lahnda" },
    { "lam", "Lamba" },
    { "lao", "Lao" },
    { "lat", "Latin" },
    { "lav", "Latvian" },
    { "lez", "Lezghian" },
    { "lim", "Limburgan" },
    { "lin", "Lingala" },
    { "lit", "Lithuanian" },
    { "lol", "Mongo" },
    { "loz", "Lozi" },
    { "ltz", "Luxembourgish" },
    { "lua", "Luba-Lulua" },
    { "lub", "Luba-Katanga" },
    { "lug", "Ganda" },
    { "lui", "Luiseno" },
    { "lun", "Lunda" },
    { "luo", "Luo" },
    { "lus", "Lushai" },
    { "mac", "Macedonian" },
    { "mad", "Madurese" },
    { "mag", "Magahi" },
    { "mah", "Marchallese" },
    { "mai", "Maithili" },
    { "mak", "Makasar" },
    { "mal", "Malayalam" },
    { "man", "Mandingo" },
    { "mao", "Maori" },
    { "map", "Austronesian" },
    { "mar", "Marathi" },
    { "mas", "Masai" },
    { "may", "Malay" },
    { "mdf", "Moksha" },
    { "mdr", "Mandar" },
    { "men", "Mende" },
    { "mga", "Middle Irish" },
    { "mic", "Mi'kmaq" },
    { "min", "Minangkabau" },
    { "mkd", "Macedonian" },
    { "mkh", "Mon-Khmer" },
    { "mlg", "Malagasy" },
    { "mlt", "Maltese" },
    { "mnc", "Manchu" },
    { "mni", "Manipuri" },
    { "mno", "Manobo" },
    { "moh", "Mohawk" },
    { "mon", "Mongolian" },
    { "mos", "Mossi" },
    { "mri", "Maori" },
    { "msa", "Malay" },
    { "mun", "Munda" },
    { "mus", "Creek" },
    { "mwl", "Mirandese" },
    { "mwr", "Marwari" },
    { "mya", "Burmese" },
    { "myn", "Mayan" },
    { "myv", "Erzya" },
    { "nah", "Nahuatl" },
    { "nai", "North American Indian" },
    { "nap", "Neapolitan" },
    { "nau", "Nauru" },
    { "nav", "Navajo" },
    { "nbl", "South Ndebele" },
    { "nde", "North Ndebele" },
    { "ndo", "Ndonga" },
    { "nds", "Low German" },
    { "nep", "Nepali" },
    { "new", "Newari" },
    { "nia", "Nias" },
    { "nic", "Niger-Kordofanian" },
    { "niu", "Niuean" },
    { "nld", "Dutch" },
    { "nno", "Norwegian Nynorsk" },
    { "nob", "Norwegian Bokmal" },
    { "nog", "Nogai" },
    { "non", "Norse" },
    { "nor", "Norwegian" },
    { "nqo", "N'Ko" },
    { "nso", "Pedi" },
    { "nub", "Nubian" },
    { "nwc", "Classical Newari" },
    { "nya", "Chichewa" },
    { "nym", "Nyamwezi" },
    { "nyn", "Nyankole" },
    { "nyo", "Nyoro" },
    { "nzi", "Nzima" },
    { "oci", "Occitan" },
    { "oji", "Ojibwa" },
    { "ori", "Oriya" },
    { "orm", "Oromo" },
    { "osa", "Osage" },
    { "oss", "Ossetian" },
    { "ota", "Ottoman" },
    { "oto", "Otomian" },
    { "paa", "Papuan" },
    { "pag", "Pangasinan" },
    { "pal", "Pahlavi" },
    { "pam", "Pampanga" },
    { "pan", "Panjabi" },
    { "pap", "Papiamento" },
    { "pau", "Palauan" },
    { "peo", "Old Persian" },
    { "per", "Persian" },
    { "phi", "Philippine" },
    { "phn", "Phoenician" },
    { "pli", "Pali" },
    { "pol", "Polish" },
    { "pon", "Pohnpeian" },
    { "por", "Portuguese" },
    { "pra", "Prakrit" },
    { "pro", "Old Provencal" },
    { "pus", "Pushto" },
    { "que", "Quechua" },
    { "raj", "Rajasthani" },
    { "rap", "Rapanui" },
    { "rar", "Rarotongan" },
    { "roa", "Romance" },
    { "roh", "Romansh" },
    { "rom", "Romany" },
    { "ron", "Romanian" },
    { "rum", "Romanian" },
    { "run", "Rundi" },
    { "rup", "Aromanian" },
    { "rus", "Russian" },
    { "sad", "Sandawe" },
    { "sag", "Sango" },
    { "sah", "Yakut" },
    { "sai", "South American Indian" },
    { "sal", "Salishan" },
    { "sam", "Samaritan" },
    { "san", "Sanskrit" },
    { "sas", "Sasak" },
    { "sat", "Santali" },
    { "scn", "Sicilian" },
    { "sco", "Scots" },
    { "sel", "Selkup" },
    { "sem", "Semitic" },
    { "sga", "Old Irish" },
    { "sgn", "Sign" },
    { "shn", "Shan" },
    { "sid", "Sidamo" },
    { "sin", "Sinhala" },
    { "sio", "Siouan" },
    { "sit", "Sino-Tibetan" },
    { "sla", "Slavic" },
    { "slk", "Slovak" },
    { "slo", "Slovak" },
    { "slv", "Slovenian" },
    { "sma", "Southern Sami" },
    { "sme", "Northern Sami" },
    { "smi", "Sami" },
    { "smj", "Lule Sami" },
    { "smn", "Inari Sami" },
    { "smo", "Samoan" },
    { "sms", "Skolt Sami" },
    { "sna", "Shona" },
    { "snd", "Sindhi" },
    { "snk", "Soninke" },
    { "sog", "Sogdian" },
    { "som", "Somali" },
    { "son", "Songhai" },
    { "sot", "Southern Sotho" },
    { "spa", "Spanish" },
    { "sqi", "Albanian" },
    { "srd", "Sardinian" },
    { "srn", "Sranan Tongo" },
    { "srp", "Serbian" },
    { "srr", "Serer" },
    { "ssa", "Nilo-Saharan" },
    { "ssw", "Swati" },
    { "suk", "Sukuma" },
    { "sun", "Sundanese" },
    { "sus", "Susu" },
    { "sux", "Sumerian" },
    { "swa", "Swahili" },
    { "swe", "Swedish" },
    { "syc", "Classical Syriac" },
    { "syr", "Syriac" },
    { "tah", "Tahitian" },
    { "tai", "Tai" },
    { "tam", "Tamil" },
    { "tat", "Tatar" },
    { "tel", "Telugu" },
    { "tem", "Timne" },
    { "ter", "Tereno" },
    { "tet", "Tetum" },
    { "tgk", "Tajik" },
    { "tgl", "Tagalog" },
    { "tha", "Thai" },
    { "tib", "Tibetan" },
    { "tig", "Tigre" },
    { "tir", "Tigrinya" },
    { "tiv", "Tiv" },
    { "tkl", "Tokelau" },
    { "tlh", "Klingon" },
    { "tli", "Tlingit" },
    { "tmh", "Tamashek" },
    { "tog", "Tonga" },
    { "ton", "Tonga" },
    { "tpi", "Tok Pisin" },
    { "tsi", "Tsimshian" },
    { "tsn", "Tswana" },
    { "tso", "Tsonga" },
    { "tuk", "Turkmen" },
    { "tum", "Tumbuka" },
    { "tup", "Tupi" },
    { "tur", "Turkish" },
    { "tut", "Altaic" },
    { "tvl", "Tuvalu" },
    { "twi", "Twi" },
    { "tyv", "Tuvinian" },
    { "udm", "Udmurt" },
    { "uga", "Ugaritic" },
    { "uig", "Uyghur" },
    { "ukr", "Ukrainian" },
    { "umb", "Umbundu" },
    { "und", "Undetermined" },
    { "urd", "Urdu" },
    { "uzb", "Uzbek" },
    { "vai", "Vai" },
    { "ven", "Venda" },
    { "vie", "Vietnamese" },
    { "vol", "Volapuk" },
    { "vot", "Votic" },
    { "wak", "Wakashan" },
    { "wal", "Wolaitta" },
    { "war", "Waray" },
    { "was", "Washo" },
    { "wel", "Welsh" },
    { "wen", "Sorbian" },
    { "wln", "Walloon" },
    { "wol", "Wolof" },
    { "xal", "Kalmyk" },
    { "xho", "Xhosa" },
    { "yao", "Yao" },
    { "yap", "Yapese" },
    { "yid", "Yiddish" },
    { "yor", "Yoruba" },
    { "ypk", "Yupik" },
    { "zap", "Zapotec" },
    { "zbl", "Blissymbolics" },
    { "zen", "Zenaga" },
    { "zgh", "Standard Moroccan Tamazight" },
    { "zha", "Zhuang" },
    { "zho", "Chinese" },
    { "znd", "Zande" },
    { "zul", "Zulu" },
    { "zun", "Zuni" },
    { "zza", "Zazaki" }
};